// Native samplers and tailers adapted from the CE plugin registry.
// These are distinct from OpenTelemetry source configuration templates.
export type NativePlugin = {
  id: string;
  name: string;
  category: string;
  description: string;
  access: string;
  signals: string[];
  metrics: string[];
  fields: string[];
};

export const nativePlugins: NativePlugin[] = [
  {
    id: "cloud-inventory",
    name: "Cloud inventory",
    category: "Infrastructure",
    description:
      "Resource inventory from AWS, Azure, and GCP with shared cloud identity.",
    access:
      "Run with an authenticated provider CLI and scoped inventory permissions.",
    signals: ["Metrics", "Logs"],
    metrics: [],
    fields: [
      "interval_sec",
      "timeout_sec",
      "providers",
      "max_resources",
      "aws_region",
      "aws_command",
      "azure_command",
      "gcloud_command",
    ],
  },
  {
    id: "container",
    name: "Containers",
    category: "Infrastructure",
    description:
      "Container CPU, memory, I/O, network activity, and lifecycle state.",
    access: "Access the configured local container runtime.",
    signals: ["Metrics"],
    metrics: [],
    fields: [
      "interval_sec",
      "runtime",
      "docker_socket",
      "containerd_socket",
      "podman_socket",
      "include_containers",
      "exclude_containers",
      "collect_network",
    ],
  },
  {
    id: "cpu",
    name: "CPU",
    category: "Infrastructure",
    description:
      "Per-core utilization, load averages, clock speed, and processor state.",
    access: "Read local host CPU counters.",
    signals: ["Metrics"],
    metrics: [
      "cpu.percentUtilisation",
      "cpu.percentUserTime",
      "cpu.percentKernelTime",
      "cpu.percentIdleTime",
      "cpu.percentWaitTime",
      "cpu.percentNiceTime",
      "cpu.percentIrqTime",
      "cpu.percentSoftIrqTime",
    ],
    fields: ["interval_sec"],
  },
  {
    id: "disk",
    name: "Disk & filesystem",
    category: "Infrastructure",
    description:
      "Partition capacity, inode availability, device I/O, and disk latency.",
    access: "Read the selected filesystems and device counters.",
    signals: ["Metrics"],
    metrics: [
      "disk.totalSpace",
      "disk.usedSpace",
      "disk.freeSpace",
      "disk.percentageUsed",
      "disk.totalInodes",
      "disk.freeInodes",
      "disk.percentageFreeInodes",
      "disk.statusCode",
    ],
    fields: [
      "interval_sec",
      "auto_detect",
      "view_profile",
      "exclude_partitions",
      "maximum_partitions",
      "check_nfs_partitions",
      "match_exact_partitions",
      "warn_threshold",
    ],
  },
  {
    id: "fkm",
    name: "File keyword monitor",
    category: "Files & logs",
    description:
      "Detect important log patterns, track severity, and follow conditions as they clear.",
    access:
      "Grant read access to the selected files and configure match patterns.",
    signals: ["Metrics"],
    metrics: [
      "fkm.filesMonitored",
      "fkm.filesInError",
      "fkm.filesInWarning",
      "fkm.filesNotFound",
      "fkm.fileSize",
      "fkm.secondsSinceLastModified",
      "fkm.secondsSinceLastTrigger",
      "fkm.triggerCount",
    ],
    fields: [
      "enabled",
      "execution_target",
      "execution_mode",
      "interval_sec",
      "timeout_sec",
      "jitter_percent",
      "multiple_trigger_mode",
      "continue_trigger_scan",
    ],
  },
  {
    id: "ftm",
    name: "File transmission monitor",
    category: "Files & logs",
    description:
      "Track expected file arrivals against monitoring windows and calendar schedules.",
    access:
      "Grant read access to the selected directories and define arrival windows.",
    signals: ["Metrics"],
    metrics: [
      "totalFilesExpected",
      "filesDelayed",
      "lateArrivals",
      "totalReceived",
      "filesIncomplete",
      "filesWarning",
      "filesCritical",
      "delaySeconds",
    ],
    fields: [
      "enabled",
      "execution_target",
      "execution_mode",
      "interval_sec",
      "timeout_sec",
      "jitter_percent",
      "files_json",
      "holidays_json",
    ],
  },
  {
    id: "hardware",
    name: "Host hardware",
    category: "Infrastructure",
    description:
      "CPU, memory, swap, uptime, and time synchronization in one host view.",
    access: "Read host hardware and operating system state.",
    signals: ["Metrics"],
    metrics: [
      "hardware.coresPerCPU",
      "hardware.cpuClockSpeed",
      "hardware.cpuUtilisation",
      "hardware.hyperThreadingEnabled",
      "hardware.memoryAvailable",
      "hardware.memoryAvailablePct",
      "hardware.memoryBuffers",
      "hardware.memoryCached",
    ],
    fields: [
      "interval_sec",
      "include_slab_memory",
      "include_buffers_and_cache",
      "cpu_smoothing",
      "time_sync_checking",
    ],
  },
  {
    id: "kubernetes",
    name: "Kubernetes",
    category: "Infrastructure",
    description:
      "Nodes, pods, workloads, storage, and autoscaling from the cluster APIs.",
    access: "Use scoped Kubernetes API and metrics API access.",
    signals: ["Metrics"],
    metrics: [],
    fields: [
      "interval_sec",
      "kubeconfig_path",
      "api_server_url",
      "bearer_token",
      "namespaces",
      "exclude_namespaces",
      "collect_nodes",
      "collect_pods",
    ],
  },
  {
    id: "log-tailer",
    name: "Log tailer",
    category: "Files & logs",
    description:
      "Turn appended local log lines into structured records for investigation.",
    access: "Grant read access to the selected log paths.",
    signals: ["Logs"],
    metrics: [],
    fields: [
      "interval_sec",
      "paths",
      "start_at_end",
      "max_lines_per_tick",
      "discover_docker",
      "docker_log_paths",
      "discover_kubernetes",
      "kubernetes_log_paths",
    ],
  },
  {
    id: "network",
    name: "Network interfaces",
    category: "Infrastructure",
    description:
      "Interface throughput, packet rates, errors, and dropped packets.",
    access: "Read counters from the selected network interfaces.",
    signals: ["Metrics"],
    metrics: [
      "net.rxKBs",
      "net.txKBs",
      "net.rxPacketsPs",
      "net.txPacketsPs",
      "net.rxBytes",
      "net.txBytes",
      "net.rxPackets",
      "net.txPackets",
    ],
    fields: [
      "interval_sec",
      "include_interfaces",
      "show_loopback",
      "show_virtual",
    ],
  },
  {
    id: "process",
    name: "Processes",
    category: "Processes & services",
    description:
      "Process counts, resource usage, and the state of critical application processes.",
    access: "Read process state on the target host.",
    signals: ["Metrics"],
    metrics: [
      "proc.totalProcesses",
      "proc.matchedProcesses",
      "proc.monitoredNames",
      "proc.namesWithMatches",
      "proc.zombieProcesses",
      "proc.instanceCount",
      "proc.percentCPU",
      "proc.scaledPercentCPU",
    ],
    fields: [
      "enabled",
      "execution_target",
      "execution_mode",
      "interval_sec",
      "timeout_sec",
      "jitter_percent",
      "display_mode",
      "max_rows",
    ],
  },
  {
    id: "prometheus",
    name: "Prometheus scrape",
    category: "Network & endpoints",
    description:
      "Fetch metrics directly from approved Prometheus exposition endpoints.",
    access: "Allow access to the target metrics endpoints.",
    signals: ["Metrics"],
    metrics: [],
    fields: [
      "interval_sec",
      "timeout_sec",
      "targets",
      "scheme",
      "metrics_path",
      "bearer_token",
      "basic_user",
      "basic_pass",
    ],
  },
  {
    id: "snmp",
    name: "SNMP network devices",
    category: "Network & endpoints",
    description:
      "Collect device health and network counters from SNMP-enabled infrastructure.",
    access: "Configure approved device targets and SNMP credentials.",
    signals: ["Metrics"],
    metrics: [],
    fields: [
      "interval_sec",
      "timeout_sec",
      "targets",
      "targets_json",
      "community",
      "version",
      "port",
      "retries",
    ],
  },
  {
    id: "sql",
    name: "SQL query sampler",
    category: "Databases",
    description:
      "Collect query results as operational metrics with scheduled or on-demand sampling.",
    access: "Use read-only database credentials and a bounded query timeout.",
    signals: ["Metrics"],
    metrics: ["sql.<sampler>.<column>"],
    fields: [
      "enabled",
      "execution_mode",
      "execution_target",
      "interval_sec",
      "timeout_sec",
      "run_now_timeout_sec",
      "pool_max_open",
      "pool_max_idle",
    ],
  },
  {
    id: "systemd",
    name: "Systemd services",
    category: "Processes & services",
    description:
      "Unit health and lifecycle state for the Linux services your applications depend on.",
    access: "Read the selected systemd service units.",
    signals: ["Metrics"],
    metrics: [
      "systemd.active",
      "systemd.status",
      "systemd.totalServices",
      "systemd.activeServices",
      "systemd.failedServices",
    ],
    fields: ["interval_sec", "services"],
  },
  {
    id: "toolkit",
    name: "Toolkit",
    category: "Custom operations",
    description:
      "Bring existing operational scripts into scheduled samplers and shared dataviews.",
    access:
      "Approve executable paths and bound runtime, output, and resource use.",
    signals: ["Metrics"],
    metrics: [
      "toolkit.rows",
      "toolkit.statusCode",
      "toolkit.execDurationSeconds",
      "toolkit.failedSamples",
      "toolkit.<column>",
    ],
    fields: [
      "enabled",
      "execution_target",
      "execution_mode",
      "interval_sec",
      "timeout_sec",
      "run_now_timeout_sec",
      "jitter_percent",
      "sampler_script",
    ],
  },
  {
    id: "website-monitor",
    name: "Website monitor",
    category: "Network & endpoints",
    description:
      "Track website availability, response time, and expected status from your network.",
    access:
      "Configure the target URL and allow access from the collection location.",
    signals: ["Metrics"],
    metrics: [
      "website.totalTime",
      "website.dnsLookup",
      "website.tcpConnection",
      "website.tlsHandshake",
      "website.serverProcessing",
      "website.contentDownload",
      "website.samplingStatusCode",
      "website.httpStatus",
    ],
    fields: [
      "display_name",
      "target_url",
      "interval_sec",
      "timeout_sec",
      "jitter_percent",
      "expected_status",
      "follow_redirects",
      "verify_ssl",
    ],
  },
  {
    id: "x-http",
    name: "HTTP & HTTPS",
    category: "Network & endpoints",
    description:
      "Measure DNS, connection, TLS, server response, and download timings.",
    access: "Allow outbound access to the selected HTTP or HTTPS endpoints.",
    signals: ["Metrics"],
    metrics: [
      "xhttp.totalTime",
      "xhttp.dnsLookup",
      "xhttp.tcpConnection",
      "xhttp.sslHandshake",
      "xhttp.serverProcessing",
      "xhttp.contentDownload",
      "xhttp.statusCode",
      "xhttp.uptimePercent",
    ],
    fields: [
      "interval_sec",
      "timeout_sec",
      "jitter_percent",
      "target_urls_json",
      "expected_status",
      "follow_redirects",
      "verify_ssl",
      "user_agent",
    ],
  },
  {
    id: "x-ping",
    name: "X Ping",
    category: "Network & endpoints",
    description:
      "Check private endpoint reachability, round-trip latency, and packet loss.",
    access:
      "Allow access to the configured destinations and required network privileges.",
    signals: ["Metrics"],
    metrics: [
      "xping.turnaroundTime",
      "xping.failurePercent",
      "xping.statusCode",
      "xping.targets",
      "xping.reachable",
      "xping.unreachable",
    ],
    fields: [
      "enabled",
      "execution_target",
      "execution_mode",
      "interval_sec",
      "timeout_sec",
      "jitter_percent",
      "target_nodes_json",
      "recv_interfaces",
    ],
  },
  {
    id: "x-traffic",
    name: "X Traffic",
    category: "Network & endpoints",
    description:
      "Inspect traffic rates and packet behavior near the systems you operate.",
    access:
      "Configure monitored interfaces and required packet capture permissions.",
    signals: ["Metrics"],
    metrics: [
      "xtraffic.packetSendRate",
      "xtraffic.packetReceiveRate",
      "xtraffic.dataSendRateKBs",
      "xtraffic.dataReceiveRateKBs",
      "xtraffic.connections",
      "xtraffic.bytesSent",
      "xtraffic.bytesReceived",
      "xtraffic.packetsSent",
    ],
    fields: [
      "enabled",
      "execution_target",
      "execution_mode",
      "interval_sec",
      "timeout_sec",
      "jitter_percent",
      "display_mode",
      "heartbeat_timeout_sec",
    ],
  },
];

export const pluginCategories = [
  ...new Set(nativePlugins.map((plugin) => plugin.category)),
];
